name: Enforce source branch

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR originates from staging branch
        if: github.head_ref != 'staging'
        run: |
          echo "::error::PRs to main must come from the staging branch. Please merge your changes into staging first, then open a PR from staging to main."
          exit 1

      - name: Source branch verified
        if: github.head_ref == 'staging'
        run: echo "Source branch is 'staging'. Check passed."
