name: Enforce source branch

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR originates from test branch
        if: github.head_ref != 'test'
        run: |
          echo "::error::PRs to main must come from the test branch. Please merge your changes into test first, then open a PR from test to main."
          exit 1

      - name: Source branch verified
        if: github.head_ref == 'test'
        run: echo "Source branch is 'test'. Check passed."
